return {
    default={
        name="d-tracker",
        pencil_icon="pencil_icon.PPM"
    },
    stain={
        name="d-tracker-stain",
        pencil_icon="pencil_icon_stain.PPM"
    },
    klinik={
        name="d-tracker-klinik",
        pencil_icon="pencil_icon_klinik.PPM"
    },
    monochrome={
        name="d-tracker-monochrome",
        pencil_icon="pencil_icon_monochrome.PPM"
    },
    gradient={
        name="d-tracker-gradient",
        pencil_icon="pencil_icon_gradient.PPM"
    },
    mint={
        name="d-tracker-mint",
        pencil_icon="pencil_icon_mint.PPM"
    }
}
