name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: apt-update
      run: sudo apt-get update -qq
    - name: Install Linux Build Dependencies
      run: sudo apt-get install -y automake libtool libx11-dev libxft2-dev libxext-dev libxxf86vm-dev libdbus-1-dev
    - name: Linux Build
      run: make
    - name: Install Unit Testing dependencies
      run: sudo apt-get install -y lua5.1 lua-busted
    - name: Unit Tests
      run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/ && make test
    - name: Clear build
      run: make clean
    - name: Install cross-compilation dependencies
      run: sudo apt-get install -y mingw-w64
    - name: Windows Build
      run: make release_windows
